let dados = [
    {
        titulo : "São Paulo (Brasil)",
        clima : "Subtropical, com verões quentes e úmidos e invernos amenos.",
        valor : "R$300,00 (estimativa)",
        curiosidades : "Maior cidade da América do Sul, conhecida por sua diversidade cultural e economia vibrante.",
        populacao : "Aproximadamente 12,3 milhões de habitantes.",
        lugares : "Avenida Paulista, Parque Ibirapuera, Museu de Arte de São Paulo (MASP), Pinacoteca.",
        link : "https://blog.blablacar.com.br/destinos/o-que-fazer-em-sao-paulo",
        imagem : "https://clubelatino.com.br/wp-content/uploads/2018/08/sao-paulo.jpg",
        tags : "megacidade cultura negócios gastronomia av paulista ibirapuera masp sao paulo",
    },
    {
        titulo: "Rio de Janeiro (Brasil)",
        clima: "Tropical úmido, com verões quentes e chuvosos.",
        valor: "R$400,00 (estimativa)",
        curiosidades: "Cidade maravilhosa, famosa por suas praias e o Carnaval.",
        populacao: "Aproximadamente 6,7 milhões de habitantes.",
        lugares: "Cristo Redentor, Pão de Açúcar, Copacabana, Ipanema.",
        link: "https://www.viajenaviagem.com/destino/rio-de-janeiro/",
        imagem : "https://turismoenrio.com/img/cristo-redentor-1.webp",
        tags : "praias carnaval cristo redentor pão de açúcar copacabana ipanema",
    },
    {
        titulo: "Lisboa (Portugal)",
        clima: "Mediterrânico, com verões quentes e secos e invernos amenos.",
        valor: "€250,00 (estimativa)",
        curiosidades: "Capital de Portugal, conhecida por sua história rica e arquitetura medieval.",
        populacao: "Aproximadamente 505 mil habitantes.",
        lugares: "Torre de Belém, Castelo de São Jorge, Alfama.",
        link: "https://www.viajenaviagem.com/destino/lisboa/",
        imagem : "https://static.portugalbywine.com/media//MULTIMEDIA/FOTOS/241/0003E8EE76BE3A.jpg",
        tags : "história arquitetura fado,pastel de nata belém alfama",
    },
    {
        titulo: "Barcelona (Espanha)",
        clima: "Mediterrânico, com verões quentes e secos e invernos amenos.",
        valor: "€350,00 (estimativa)",
        curiosidades: "Cidade cosmopolita, famosa pela arquitetura de Gaudí e pela vida noturna.",
        populacao: "Aproximadamente 1,6 milhões de habitantes.",
        lugares: "Sagrada Família, Park Güell, La Rambla.",
        link: "https://www.viajenaviagem.com/destino/barcelona/",
        imagem : "https://www.melhoresdestinos.com.br/wp-content/uploads/2019/02/passagens-aereas-barcelona-capa2019-01.jpg",
        tags : "arquitetura gaudi sagrada familia park guell la rambla futebol camp nou",
    },
    {
        titulo: "Madrid (Espanha)",
        clima: "Continental, com verões quentes e secos e invernos frios.",
        valor: "€300,00 (estimativa)",
        curiosidades: "Capital da Espanha, conhecida por seus museus e pela vida cultural vibrante.",
        populacao: "Aproximadamente 3,2 milhões de habitantes.",
        lugares: "Prado, Reina Sofía, Puerta del Sol.",
        link: "https://www.viajenaviagem.com/destino/madri/",
        imagem : "https://th.bing.com/th/id/R.feebd30917ea0fafe1803900b4a86e47?rik=A3VYjcv7YMGrpA&riu=http%3a%2f%2fwww.progettosigillo.it%2fwp-content%2fuploads%2f2021%2f06%2fmadrid-di-notte.jpg&ehk=I7jpSksIcrGDBIoSy2KRoTqHyCpgUjTlSs5J6m2J1Ic%3d&risl=&pid=ImgRaw&r=0",
        tags : "museus arte prado reina sofia sol plaza mayor real madrid",
    },
    {
        titulo: "Paris (França)",
        clima: "Temperado oceânico, com verões amenos e invernos frios.",
        valor: "€400,00 (estimativa)",
        curiosidades: "Cidade das luzes, famosa pela Torre Eiffel e pela moda.",
        populacao: "Aproximadamente 2,1 milhões de habitantes.",
        lugares: "Torre Eiffel, Museu do Louvre, Catedral de Notre Dame.",
        link: "https://www.viajenaviagem.com/destino/paris/",
        imagem : "https://viagemeturismo.abril.com.br/wp-content/uploads/2016/11/thinkstockphotos-4549879531.jpeg?quality=70",
        tags : "romântico,moda,torre eiffel,louvre,notre dame,champ elysees,psg",
    },
    {
        titulo: "Londres (Inglaterra)",
        clima: "Temperado oceânico, com verões amenos e invernos frios.",
        valor: "£350,00 (estimativa)",
        curiosidades: "Capital da Inglaterra, conhecida por sua história rica e pela diversidade cultural.",
        populacao: "Aproximadamente 8,9 milhões de habitantes.",
        lugares: "Big Ben, Buckingham Palace, British Museum.",
        link: "https://www.viajenaviagem.com/destino/londres/",
        imagem : "https://cdn.holidayguru.es/wp-content/uploads/2016/10/Big-Ben-the-Parliament-and-doubledecker-in-London-iStock_71522637_XLARGE-2-2.jpg",
        tags : "história,cultura,big ben,buckingham,british museum,tower bridge",
    },
    {
        titulo: "Santiago (Chile)",
        clima: "Mediterrânico, com verões quentes e secos e invernos amenos.",
        valor: "CLP 200.000 (estimativa)",
        curiosidades: "Capital do Chile, conhecida por seus vinhos e pelos Andes.",
        populacao: "Aproximadamente 6,3 milhões de habitantes.",
        lugares: "Cerro San Cristóbal, La Chascona, Mercado Central.",
        link: "https://www.viajenaviagem.com/destino/santiago/",
        imagem : "https://cdn.blablacar.com/wp-content/uploads/br/2024/03/05095949/santiago-chile.webp",
        tags : "andes,vinho,cerro san cristóbal,la chascona,mercado central",
    },
    {
        titulo: "Buenos Aires (Argentina)",
        clima: "Subtropical úmido, com verões quentes e úmidos e invernos amenos.",
        valor: "ARS 15.000 (estimativa)",
        curiosidades: "Capital da Argentina, conhecida por seu tango e pela arquitetura europeia.",
        populacao: "Aproximadamente 2,9 milhões de habitantes.",
        lugares: "Obelisco, Casa Rosada, Caminito.",
        link: "https://www.viajenaviagem.com/destino/buenos-aires/",
        imagem : "https://blogmaladeviagem.com.br/wp-content/uploads/2022/11/blog-mv-buenos-aires8-1170x658.jpg.webp",
        tags : "tango,milonga,literatura,arte,arquitetura,história,futebol,Boca Juniors,River Plate", 
    },
    {
        titulo: "Nova York (Estados Unidos)",
        clima: "Continental úmido, com verões quentes e úmidos e invernos frios.",
        valor: "US$500,00 (estimativa)",
        curiosidades: "A cidade que nunca dorme, conhecida por sua diversidade cultural e economia global.",
        populacao: "Aproximadamente 8,4 milhões de habitantes.",
        lugares: "Estátua da Liberdade, Times Square, Central Park.",
        link: "https://www.viajenaviagem.com/destino/nova-york/",
        imagem : "https://www.remessaonline.com.br/blog/wp-content/uploads/2022/06/morar-em-nova-york.jpg.optimal.jpg",
        tags : "megacidade,times square,estátua da liberdade,central park,broadway new york nova iorque",
    },
    {
        titulo: "Roma (Itália)",
        clima: "Mediterrâneo, com verões quentes e secos e invernos amenos.",
        valor: "€150,00 (estimativa)",
        curiosidades: "A Cidade Eterna, berço da civilização romana e centro cultural da Itália.",
        populacao: "Aproximadamente 2,8 milhões de habitantes.",
        lugares: "Coliseu, Fontana di Trevi, Vaticano.",
        link: "https://www.viajenaviagem.com/destino/roma/",
        imagem : "https://th.bing.com/th/id/OIP.AQ_5abZ7rHc0yq9hf3M62AHaFE?rs=1&pid=ImgDetMain",
        tags : "história antiga coliseu fontana di trevi vaticano pizza pasta italia",
    }
];

